### ISSUE TITLE
Forward DataFactory to parsers/readers

### ISSUE THREAD

**Issue by bergos** [rdfjs/stream-spec#6]
The constructor of readers should have an option to define the DataFactory that is used to create Terms and Quads.

Proposal: Use an object as last parameter of the constructor with the property  `factory`

**Comment by k00ni** [comment]
What is the status here?

Using Dependency Injection here allows more flexibility. For instance, if your `Quad`- or `Term`-based implementation differs from the standard implementation. A custom factory allows custom implementations.

**Comment by elf-pavlik** [comment]
Thinking about size of browser builds, if we make factory optional and library has to include its own 'default' factory it may make it more complicated to ensure that only one data factory ends up in the build that web browser needs to fetch over the network.

Maybe we should require passing factory (or factory constructor) to the Source constructor and libraries wouldn't have to pick one as default?

Possibly another reason to ship `DataFactory` first and double check `Source`, `Sink` and `Store` interfaces.

**Comment by elf-pavlik** [comment]
resolved in #10
