### ISSUE TITLE
Parser or Transform interface

### ISSUE THREAD

**Issue by bergos** [rdfjs/stream-spec#7]
The `Source` interface doesn't define how an input stream like a file stream is feed to the `Source` instance. A common way for this would be usefull. Because the `Source` interface is not exclusive for parsers we should avoid methods like `.parse`. We can define a new name like `.transform`, which describes the input/output behavior. It would be also possible to align it to the `Sink` interface and name it `.import`. That's how the interface should look like:

```
class Transform {
    // all instance specific options must be assigned in the constructor
    constructor (options) {
      this.options = options
    } 

    transform(inputStream) {
      // outputStream implements the Source interface
      return outputStream
    }
}
```

**Comment by elf-pavlik** [comment]
@bergos can we close this issue?
